using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;

// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by '.NET Wrapper Class Generator'
//     Product Version:0.8.8181.29174
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AutoMoqExtensions.AutoMockUtils
{
    
    
    public class AutoMockParameterInfo : ParameterInfo
    {

        private System.Reflection.ParameterInfo parameterInfo;

        public AutoMockParameterInfo(System.Reflection.ParameterInfo parameterInfo)
        {
            this.parameterInfo = parameterInfo;
            paramType = AutoMockHelpers.GetAutoMockType(parameterInfo.ParameterType);
        }

        public override System.Reflection.ParameterAttributes Attributes => parameterInfo.Attributes;
        public override System.Collections.Generic.IEnumerable<System.Reflection.CustomAttributeData> CustomAttributes 
                        => parameterInfo.CustomAttributes;
       

        public override object DefaultValue => parameterInfo.DefaultValue;

        public override bool HasDefaultValue => parameterInfo.HasDefaultValue;
        public override MemberInfo Member => parameterInfo.Member;
        public override int MetadataToken => parameterInfo.MetadataToken;
        public override string Name => parameterInfo.Name;
        private readonly Type paramType;
        public override Type ParameterType => paramType;
        public override int Position => parameterInfo.Position;
        public override object RawDefaultValue => parameterInfo.RawDefaultValue;
                
        public override object[] GetCustomAttributes(Type attributeType, Boolean inherit) 
            => parameterInfo.GetCustomAttributes(attributeType, inherit);
        public override object[] GetCustomAttributes(Boolean inherit) 
            => parameterInfo.GetCustomAttributes(inherit);

        public override System.Collections.Generic.IList<System.Reflection.CustomAttributeData> GetCustomAttributesData() 
            => parameterInfo.GetCustomAttributesData();        

        public override System.Type[] GetOptionalCustomModifiers() 
            => parameterInfo.GetOptionalCustomModifiers();

        public override System.Type[] GetRequiredCustomModifiers() 
            => parameterInfo.GetRequiredCustomModifiers();
        public override bool IsDefined(Type attributeType, Boolean inherit) 
            => parameterInfo.IsDefined(attributeType, inherit);

        public override string ToString() => parameterInfo.ToString();
    }
}

